AppBundle\Entity\Image:
    exclusion_policy: ALL
    properties:
        shortId:
            groups: [image_simple, challenge_simple]
            serialized_name: id
            type: string
        originalName:
            groups: [image_admin]
        imageName:
            groups: [image_simple]
        mimeType:
            groups: [image_simple]
        size:
            groups: [image_detailed]
        challenge:
            groups: [image_detailed]
        createdAt:
            groups: [image_admin]
        updatedAt:
            groups: [image_admin]
        url:
            groups: [image_simple, challenge_simple]
